# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\nmain.proto\"*\n\x0bPingMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x0bPongMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06pingId\x18\x03 \x01(\x05\x32K\n\x0bPingService\x12<\n\x08sendPing\x12\x17.main.proto.PingMessage\x1a\x17.main.proto.PongMessageB\x0e\n\nmain.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\nmain.protoP\001'
  _globals['_PINGMESSAGE']._serialized_start=29
  _globals['_PINGMESSAGE']._serialized_end=71
  _globals['_PONGMESSAGE']._serialized_start=73
  _globals['_PONGMESSAGE']._serialized_end=131
  _globals['_PINGSERVICE']._serialized_start=133
  _globals['_PINGSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
